---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-v1-env

data:
    PORT: "8281"
  SERVICE_CHECK_URL: unset
  HEALTH_CHECK_URL: unset
  BUILD_INFO_PATH: /app/build-info.json
  SERVICE_REGISTRATION_URL: "http://consul.sweetrpg-support.svc.cluster.local:1234"
  SERVER_NAME: https://dev.sweetrpg.com/api/1/library/
