---
apiVersion: v1
kind: ConfigMap

metadata:
  name: api-env

data:
  PORT: "8281"
  SERVICE_CHECK_URL: unset
  HEALTH_CHECK_URL: unset
  GUNICORN_CMD_ARGS: "--workers 10 --timeout 30 --print-config --access-logfile - --name library-api --log-level debug --log-config /config/gunicorn-logging.conf"
