---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: sweetrpg-library-api

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dev.sweetrpg.com`) && PathPrefix(`/library/api`)
      kind: Rule
      services:
        - kind: Service
          name: sweetrpg-library-api
          port: 8281
          passHostHeader: true
          responseForwarding:
            flushInterval: 1ms
      middlewares:
        - name: strip-prefix
