---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
  - namespace.yaml
  - ../../base
  - configmaps.yaml
  - middlewares.yaml
  - ingress-route.yaml

commonLabels:
  platform: sweetrpg
  app: library
  component: api

generatorOptions:
  disableNameSuffixHash: true
