---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
    - namespace.yaml
    - ../../base
    - configmaps.yaml
    - mongodb-atlas-service-entry.yaml
patchesStrategicMerge:
    - replicas.yaml

commonLabels:
    platform: sweetrpg
    app: library
    component: api

generatorOptions:
    disableNameSuffixHash: true
