---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
    - ../../base
    - configmaps.yaml
    - hpa.yaml
    - pdb.yaml
    - mongodb-atlas-service-entry.yaml
    - destination-rules.yaml
    - secrets.yaml
    - virtual-service.yaml
patchesStrategicMerge:
    - replicas.yaml

commonLabels:
    app: library-api
    version: v1
    platform: sweetrpg
    package: library
    component: api

generatorOptions:
    disableNameSuffixHash: true
