---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-library

resources:
  - namespace.yaml
  - ../../base
  - configmaps.yaml
  - middlewares.yaml
  - ingress-route.yaml
secretGenerator:
  - name: sweetrpg-registry
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson
  - name: sweetrpg-library-api-env
    type: Opaque
    envs:
      - secrets.env
  - name: sweetrpg-library-api-config-env
    type: Opaque
    files:
      - newrelic.ini

commonLabels:
  platform: sweetrpg
  app: library
  component: api

generatorOptions:
  disableNameSuffixHash: true
