---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-api-auth

spec:
    externalSecretName: api-auth

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: "1h"
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: api-auth
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: Auth0

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-api-db

spec:
    externalSecretName: api-db

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: api-db
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/library/api/db

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-api-misc

spec:
    externalSecretName: api-misc

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: api-misc
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/library/api/misc

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-api-cache

spec:
    externalSecretName: api-cache

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: api-cache
            creationPolicy: Owner
        dataFrom:
            - extract:
                  key: /sweetrpg/support/cache/client

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret

metadata:
    name: library-api-files

spec:
    externalSecretName: api-files

    namespaceSelector:
        matchLabels:
            name: sweetrpg-library

    refreshTime: 1m

    externalSecretSpec:
        refreshInterval: 1h
        secretStoreRef:
            name: akeyless
            kind: ClusterSecretStore
        target:
            name: api-files
            creationPolicy: Owner
            template:
                type: Opaque
                data:
                    newrelic.ini: "{{ .contents | toString }}"
        data:
            - secretKey: contents
              remoteRef:
                  key: NewRelic
