---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
    name: api-v1-auth
    namespace: sweetrpg-library

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-v1-auth
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: Auth0

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
    name: api-v1-db
    namespace: sweetrpg-library

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-v1-db
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/library/api/db

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
    name: api-v1-misc
    namespace: sweetrpg-library

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-v1-misc
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/library/api/misc

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
    name: api-v1-cache
    namespace: sweetrpg-library

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-v1-cache
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: /sweetrpg/library/api/cache
