---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: sweetrpg-library-api

spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      platform: sweetrpg
      app: library
      component: api
  template:
    metadata:
      labels:
        platform: sweetrpg
        app: library
        component: api
    spec:
      serviceAccountName: sweetrpg-library-api
      imagePullSecrets:
        - name: sweetrpg-registry
      containers:
        - name: library-api-app
          image: registry.sweetrpg.com/sweetrpg-library-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sweetrpg-library-api
            - configMapRef:
                name: sweetrpg-library-api-env
            - secretRef:
                name: sweetrpg-library-api
            - secretRef:
                name: sweetrpg-library-api-env
          env:
            - name: NEW_RELIC_CONFIG_FILE
              value: /app/newrelic.ini
          ports:
            - containerPort: 8281
              name: http
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "100m"
              memory: "256M"
          livenessProbe:
            httpGet:
              path: /health/ping
              port: 8281
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ping
              port: 8281
            initialDelaySeconds: 30
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
