---
kind: Service
apiVersion: v1

metadata:
  name: library-api

spec:
  selector:
    platform: sweetrpg
    app: library
    component: api
  type: LoadBalancer
  ports:
    - name: http
      port: 8281
      targetPort: http
