---
kind: Service
apiVersion: v1

metadata:
  name: api-v1

spec:
  selector:
    platform: sweetrpg
    app: library
    component: api-v1
  type: LoadBalancer
  ports:
    - name: http
      port: 8281
      targetPort: http
