name: CI - Test and build Docker image

on:
  push:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift
  pull_request:
    branches: [develop]
    paths:
      - "Sources/**"
      - "Tests/**"
      - Package.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run tests
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: swift test # -v
      - name: Get previous tag
        id: previous-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0 # Optional fallback tag to use when no tag can be found
      - name: Get next patch version
        id: semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous-tag.outputs.tag }}
      - name: Tag repository
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.semver.outputs.patch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get docker image name
        id: set-image-name
        run: |-
          echo "IMAGE_NAME=$(echo ${{ env.GITHUB_REPOSITORY }} | cut -d'/' -f 2)" >> $GITHUB_ENV
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        env:
          IMAGE_NAME: ${{ env.GITHUB_REPOSITORY }}
        with:
          # list of Docker images to use as base name for tags
          images: |
            registry.sweetrpg.com/paulyhedral/sweetrpg-library-api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavor: |
            latest=true
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: registry.sweetrpg.com
          username: docker
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DOCKER_BUILDKIT: "1"
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          ssh: default
