name: Docker Build

on:
  # push:
  #   branches:
  #     - "develop"
  release:
      types:
          - published
          - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            registry.sweetrpg.com/sweetrpg-library-api
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.sweetrpg.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # context: .
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
      #          tags: registry.sweetrpg.com/sweetrpg-library-api:latest
      # - name: Scan image
      #   uses: sysdiglabs/scan-action@v1
      #   with:
      #     image-tag: registry.sweetrpg.com/sweetrpg-library-api:latest
      #     sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
