name: Docker Build

concurrency: docker

on:
    create:
        tags:
            - '*'
    release:
        types:
            - published
            - created
    push:
        branches:
            - develop
        tags:
            - '*'
        paths:
            - "src/**"
            - "tests/**"
            - setup.cfg
            - setup.py
            - tox.ini
            - "requirements/**"
            - Dockerfile
            - scripts/entrypoint.sh
    workflow_run:
        workflows: ["CI"]
        branches: [develop]
        types:
            - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
          initial_version: v0.0.0
          with_initial_version: true
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            registry.sweetrpg.com/sweetrpg-main-web
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.previoustag.outputs.tag }}
            type=ref,event=branch
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.sweetrpg.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # context: .
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
              BUILD_NUMBER=${{ github.run_number }}
              BUILD_JOB=${{ github.job }}
              BUILD_SHA=${{ github.sha }}
              BUILD_DATE=${{ github.event.commits[0].timestamp }}
              BUILD_VERSION=${{ steps.previoustag.outputs.tag }}
      #          tags: registry.sweetrpg.com/sweetrpg-library-api:latest
      # - name: Scan image
      #   uses: sysdiglabs/scan-action@v1
      #   with:
      #     image-tag: registry.sweetrpg.com/sweetrpg-library-api:latest
      #     sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
